/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gui_JavaPasser */

#ifndef _Included_gui_JavaPasser
#define _Included_gui_JavaPasser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gui_JavaPasser
 * Method:    pass
 * Signature: (IIC)V
 */
JNIEXPORT void JNICALL Java_gui_JavaPasser_pass
  (JNIEnv *, jclass, jint, jint, jchar);

#ifdef __cplusplus
}
#endif
#endif
