/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaWinChecker */

#ifndef _Included_JavaWinChecker
#define _Included_JavaWinChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaWinChecker
 * Method:    check_win
 * Signature: (C[[C)Z
 */
JNIEXPORT jboolean JNICALL Java_JavaWinChecker_check_1win
  (JNIEnv *, jclass, jchar, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
