/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaClassifier */

#ifndef _Included_JavaClassifier
#define _Included_JavaClassifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaClassifier
 * Method:    classifier_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JavaClassifier_classifier_1init
  (JNIEnv *, jclass);

/*
 * Class:     JavaClassifier
 * Method:    classifier_make_move
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_JavaClassifier_classifier_1make_1move
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     JavaClassifier
 * Method:    classifier_prune
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JavaClassifier_classifier_1prune
  (JNIEnv *, jclass, jint);

/*
 * Class:     JavaClassifier
 * Method:    classifier_free
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JavaClassifier_classifier_1free
  (JNIEnv *, jclass);

/*
 * Class:     JavaClassifier
 * Method:    classifier_depth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JavaClassifier_classifier_1depth
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
